/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas2.mostrarEspecificos.PanelesMostrar;

import integrador.roles.Secretario;
import java.util.ArrayList;
import java.util.Iterator;

/**
 *
 * @author franb
 */
public class PanelMostrarSecretario extends javax.swing.JPanel {

    /**
     * Creates new form PanelInfoSecretario
     */
    
    private int codigoLibroActas;
    private ArrayList <Integer> codigosAlMinisterio;
    
    public PanelMostrarSecretario() {
        initComponents();
        
        this.codigoLibroActas = 0;
        this.codigosAlMinisterio = new ArrayList<>();
    }
    
    public PanelMostrarSecretario(Secretario secretario) {
        initComponents();
        
        this.codigoLibroActas = secretario.getCodigoLibroActas();
        this.codigosAlMinisterio = secretario.getCodigosAlMinisterio();
        
        //define el texto del label numero de libro de actas
        this.labelLibroActas.setText("N° de Libro de Actas. "+this.codigoLibroActas);
        
        //define el contenido de la lista de codigos de notas al ministerio
        Iterator<Integer> iterador = this.codigosAlMinisterio.iterator();
        ArrayList<String> codigos = new ArrayList<>();
        
        while (iterador.hasNext()) {
            codigos.add(iterador.next().toString());
        }
        
        this.listaCodigos.setListData(codigos.toArray(new String[] {}));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCodigos = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        listaCodigos = new javax.swing.JList<>();
        labelLibroActas = new javax.swing.JLabel();

        labelCodigos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelCodigos.setText("Codigos de notas al Minsiterio:");
        labelCodigos.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        scrollPane.setViewportView(listaCodigos);

        labelLibroActas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelLibroActas.setText("N° de Libro de Actas: ");
        labelLibroActas.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelCodigos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
            .addComponent(labelLibroActas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelLibroActas, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCodigos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelCodigos;
    private javax.swing.JLabel labelLibroActas;
    private javax.swing.JList<String> listaCodigos;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
