/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas2.mostrarEspecificos.PanelesMostrar;

import integrador.roles.Profesor;

/**
 *
 * @author franb
 */
public class PanelMostrarProfesor extends javax.swing.JPanel {

    private String titulo,materia;
    
    /**
     * Creates new form PanelInfoProfesor
     */
    public PanelMostrarProfesor() {
        initComponents();
        
        titulo = "";
        materia = "";
    }
    
    public PanelMostrarProfesor(Profesor profesor) {
        initComponents();
        
        titulo = profesor.getTitulo();
        materia = profesor.getMateria();
        
        
        this.labelTitulo.setText("Título: "+titulo);
        this.labelMateria.setText("Materia: "+materia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelMateria = new javax.swing.JLabel();

        labelTitulo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelTitulo.setText("Titulo: ");
        labelTitulo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        labelMateria.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelMateria.setText("Materia:");
        labelMateria.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {labelMateria, labelTitulo});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {labelMateria, labelTitulo});

    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelMateria;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
