/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas2.mostrarEspecificos.PanelesMostrar;

import integrador.horarios.Horario;
import integrador.horarios.HorarioSemana;
import integrador.roles.Preceptor;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author franb
 */
public class PanelMostrarPreceptor extends javax.swing.JPanel {

    
    
    private HorarioSemana horarioSupervicion;
    /**
     * Creates new form PanelInfoPreceptor
     */
    public PanelMostrarPreceptor() {
        initComponents();
        
        this.horarioSupervicion = new HorarioSemana();
        
        DefaultTableModel modeloTablaHorariosTrabajo = new javax.swing.table.DefaultTableModel(
            new Object [][] {
            
            },
            new String [] {
                "Dia", "Horario de Entrada", "Horario de Salida"
            }
        );
        
        this.TablaHorariosSupervision.setModel(modeloTablaHorariosTrabajo);
    }
    
    public PanelMostrarPreceptor(Preceptor preceptor) {
        initComponents();

        this.horarioSupervicion = preceptor.getHorarioSupervicion();
        
        DefaultTableModel modeloTablaHorariosTrabajo = new javax.swing.table.DefaultTableModel(
            new Object [][] {
            
            },
            new String [] {
                "Dia", "Horario de Entrada", "Horario de Salida"
            }
        );
        
        for (Horario hora : this.horarioSupervicion.getRutina() ) {
            modeloTablaHorariosTrabajo.addRow(new String[] {hora.pasarDiaAEspañol(),hora.getHoraDeInicio().toString(),hora.getHoraDeFin().toString()});
        }
        this.TablaHorariosSupervision.setModel(modeloTablaHorariosTrabajo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelHorariosSupervision = new javax.swing.JLabel();
        ScrollPaneTabla = new javax.swing.JScrollPane();
        TablaHorariosSupervision = new javax.swing.JTable();

        labelHorariosSupervision.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelHorariosSupervision.setText("Horarios de Supervisión:");
        labelHorariosSupervision.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        TablaHorariosSupervision.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dia", "Horario de Entrada", "Horario de Salida"
            }
        ));
        TablaHorariosSupervision.setEnabled(false);
        ScrollPaneTabla.setViewportView(TablaHorariosSupervision);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelHorariosSupervision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ScrollPaneTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelHorariosSupervision, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPaneTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPaneTabla;
    private javax.swing.JTable TablaHorariosSupervision;
    private javax.swing.JLabel labelHorariosSupervision;
    // End of variables declaration//GEN-END:variables
}
